services:
  # Local S3 Storage simulator (Optional if using AWS, but good for local dev)
  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ROOT=/data
    volumes:
      - rustfs_data:/data

volumes:
  rustfs_data:
